# Function to perform and report svm results

.svmclass_rotu <- function(level, mode, 
                          incr = 10, perms = NULL,
                          permute_dep = T,
                          pp = 16, skip_nohits = T,
                          otus = det$rOTU_clr,
                          otu_tax = det$rotu_tax,
                          map = det$rmap) {
  # level: taxonomic level, accepts phylum, class, order
  # mode: oxic state
  # incr: incremental increase in OTU subset when working with large groups
  # perms: specify the permutations to run; autogenerated if NULL
  # permute_dep: runs additional analysis with permuted response variable
  # pp: base perms if perms and max_perms are NULL. 
  #   Default is 16 respectively.
  # skip_nohits: skips analysis on the No hits group if T
  
  # IMPORTANT NOTE: Assumes that the specified mapping vector is in the map argument
  
  # Report time
  cat("Function started", as.character(Sys.time())[1], "\n")
  
  # Set up permutations
  if (is.null(perms)) {
    perms <- matrix(ncol = pp[1], nrow = round(0.25 * nrow(otus)), NA) 
    for (k in seq(pp[1])) {
      perms[, k] <- sample(nrow(otus), round(0.25 * nrow(otus))) 
    }
    cat("Setting number of perms to", pp[1], "\n")
  } 
  
  # Switch functions to determine data input
  taxa <- switch(level,
                 phylum = names(det$phylum)[det$phylumorder[1:10]],
                 class = names(det$class)[det$classorder[1:11]],
                 order = names(det$order)[det$orderorder[2:11]],
                 family = names(det$family)[det$familyorder[1:11]])
  
  dep <- switch(mode,
                quart = map[, "oxy_quart"],
                tert = map[, "oxy_tert"],
                bin = map[, "oxy_bin"])
  
  # Pick number of OTUs
  pick_topn <- function(n, level, taxon, otu_tax) {
    # gives OTU number for top n otus in chosen taxon
    df <- which(otu_tax[, level] %in% taxon)
    csums <- rowSums(otu_tax[df, 10:ncol(otu_tax)])
    topn <- names(csums[order(csums, decreasing = T)][1:n])
    if(any(is.na(topn))) {
      topn <- topn[!is.na(topn)]
    }
    topn
  }
  
  # Model one taxon
  one_taxon <- function(taxon) {
    # preallocate output
    preds <- list()
    
    if (!is.null(incr)) {
      notus <- length(which(otu_tax[, level] %in% taxon))
      if (notus > incr) {
        sqnc <- c(seq(from = 10, to = ceiling(notus/incr)*incr, by = incr), notus)
      } else {
        sqnc <- notus
      }
      
      # preallocate output
      tperm <- as.data.frame(matrix(NA, ncol = length(sqnc), nrow = ncol(perms)))
      names(tperm) <- paste0(sqnc, "_otus"); rownames(tperm) <- paste("perm", seq(ncol(perms)))
      if (permute_dep) pperm <- tperm; rownames(pperm) <- paste0(rownames(tperm), "_p")
    }  
    
    
    # for each iteration
    for (p in seq(ncol(perms))) {
      cat("base permutation", p, "\n")
      
      preds[[p]] <- as.data.frame(matrix(NA, ncol = length(sqnc) + 1, nrow = nrow(perms)))
      names(preds[[p]]) <- c("answer", names(tperm))
      
      if (!is.null(incr)) {
        # For each incremental increase in OTU numbers
        for (f in sqnc) {
          # create data set to analyse
          train_data <- cbind(otus[, pick_topn(n = f, level = level, 
                                               taxon = taxon, otu_tax = otu_tax)],
                              dep = dep)
          
          # set up data subsets
          training <- train_data[-perms[, p], ]
          test <- train_data[perms[, p], ]
          preds[[p]][, 1] <- test$dep
          # Run analysis
          fit <- caret::train(
            dep ~ .,
            data = training,
            method = "svmRadial",
            trControl = trainControl(method = "cv", number = 10),
            tuneLength = 5, 
            scale = F)
          pred <- predict(fit, test)
          preds[[p]][, which(sqnc == f) + 1] <- pred
          tperm[p, which(sqnc == f)] <- length(which(pred == test$dep))
          
          # if permute_dep
          if (permute_dep) {
            
            # create data set to analyse
            train_data$dep <- sample(train_data$dep)
            # set up data subsets
            training <- train_data[-perms[, p], ]
            test <- train_data[perms[, p], ]
            
            # Run analysis
            fit <- caret::train(
              dep ~ .,
              data = training,
              method = "svmRadial",
              trControl = trainControl(method = "cv", number = 10),
              tuneLength = 5, 
              scale = F)
            pred <- predict(fit, test)
            pperm[p, which(sqnc == f)] <- length(which(pred == test$dep))
          }
        } # end sqnc (incremental OTU increase)
      } 
      else {
        # if not incremental OTU increase
        # preallocate output
        tperm <- as.data.frame(matrix(NA, ncol = 1, nrow = ncol(perms)))
        names(tperm) <- taxon; rownames(tperm) <- paste("perm", seq(ncol(perms)))
        if (permute_dep) pperm <- tperm; rownames(pperm) <- paste0(rownames(tperm), "_p")
        
        preds[[p]] <- matrix(NA, ncol = 2, nrow = nrow(perms))
        names(preds[[p]]) <- c("answer", taxon)
        
        # create data set to analyse
        train_data <- cbind(otus[, which(otu_tax[, level] %in% taxon)], dep = dep)
        # set up data subsets
        training <- train_data[-perms[, p], ]
        test <- train_data[perms[, p], ]
        preds[[p]][, 1] <- test$dep
        # Run analysis
        fit <- caret::train(
          dep ~ .,
          data = training,
          method = "svmRadial",
          trControl = trainControl(method = "cv", number = 10),
          tuneLength = 5, 
          scale = F)
        pred <- predict(fit, test)
        preds[[p]][, 2] <- pred
        tperm[p, 1] <- length(which(pred == test$dep))
        
        # if permute_dep
        if (permute_dep) {
          # create data set to analyse
          train_data$dep <- sample(train_data$dep)
          # set up data subsets
          training <- train_data[-perms[, p], ]
          test <- train_data[perms[, p], ]
          
          # Run analysis
          fit <- caret::train(
            dep ~ .,
            data = training,
            method = "svmRadial",
            trControl = trainControl(method = "cv", number = 10),
            tuneLength = 5, 
            scale = F)
          pred <- predict(fit, test)
          pperm[p, 1] <- length(which(pred == test$dep))
        }
      } # end not incremental OTU increase
      
    } # end perms
    
    tout <- list(
      tperm = tperm,
      preds = preds
    )
    if (permute_dep) tout[["pperm"]] <- pperm
    tout
  }

  # Preallocate output
  out <- list()
  
  # For loop
  for (taxon in taxa) {
    if (skip_nohits & (taxon == "No hits"))
      warning("Skipping No hits!")
    else {
      cat("Modelling", taxon, "\n")
      out[[taxon]] <- one_taxon(taxon) # run model for base perms
      out[[taxon]]$opt_otus <- which.max(apply(out[[taxon]]$tperm, 2, median))
      notu <- as.numeric(strsplit(names(out[[taxon]]$tperm[out[[taxon]]$opt_otus]), split = "_")[[1]][1])
    }
  }
  cat("Function ended", as.character(Sys.time()[1]), "\n")
  
  out
}

# split at 1-5 vs 6-7 for balancing
det$rmap$oxy_bin <- "high"
det$rmap$oxy_bin[det$rmap$oxy_cat %in% c(6, 7)] <- "loan"

# split tert at 1-5 v 6 v 7
det$rmap$oxy_tert <- det$rmap$oxy_cat
det$rmap$oxy_tert[det$rmap$oxy_tert %in% 1:5] <- "high"
det$rmap$oxy_tert[det$rmap$oxy_tert == 6] <- "low"
det$rmap$oxy_tert[det$rmap$oxy_tert == 7] <- "anox"

# split at 1-4 v 5 v 6 v 7 for balancing
det$rmap$oxy_quart <- det$rmap$oxy_cat
det$rmap$oxy_quart[det$rmap$oxy_quart %in% 1:4] <- "high"
det$rmap$oxy_quart[det$rmap$oxy_quart == 5] <- "mid"
det$rmap$oxy_quart[det$rmap$oxy_quart == 6] <- "low"
det$rmap$oxy_quart[det$rmap$oxy_quart == 7] <- "anox"

set.seed(123) # set seed to ensure reproducible results
svmclass <- list() # create output list
# generate 128 random permutations
svmclass$perms <- matrix(ncol = 128, nrow = round(0.25 * nrow(det$rOTU)), NA) 
for (k in seq(128)) {
  svmclass$perms[, k] <- sample(nrow(det$rOTU), round(0.25 * nrow(det$rOTU))) 
}

# phylum level
svmclass$rphylum_bin <- .svmclass_rotu(level = "phylum", mode = "bin", incr = 20, perms = svmclass$perms) 
svmclass$rphylum_tert <- .svmclass_rotu(level = "phylum", mode = "tert", incr = 20, perms = svmclass$perms)
svmclass$rphylum_quart <- .svmclass_rotu(level = "phylum", mode = "quart", incr = 20, perms = svmclass$perms) 
# class level
svmclass$rclass_bin <- .svmclass_rotu(level = "class", mode = "bin", incr = 20, perms = svmclass$perms)
svmclass$rclass_tert <- .svmclass_rotu(level = "class", mode = "tert", incr = 20, perms = svmclass$perms)
svmclass$rclass_quart <- .svmclass_rotu(level = "class", mode = "quart", incr = 20, perms = svmclass$perms)
# order level
svmclass$rorder_bin <- .svmclass_rotu(level = "order", mode = "bin", incr = 20, perms = svmclass$perms) 
svmclass$rorder_tert <- .svmclass_rotu(level = "order", mode = "tert", incr = 20, perms = svmclass$perms)
svmclass$rorder_quart <- .svmclass_rotu(level = "order", mode = "quart", incr = 20, perms = svmclass$perms) 
